/**
 * Created by qhyang on 2018/2/9.
 */

const INIT_PLAYER_MODULE = "INIT_PLAYER_MODULE";
const INIT_QUEUE_MODULE = "INIT_QUEUE_MODULE";

const REGISTER_ON_PROGRESS_HANDLER = "REGISTER_ON_PROGRESS_HANDLER";
const PLAY_TRACK = "PLAY_TRACK";
const STOP_PLAYBACK = "STOP_PLAYBACK";
const RESUME_PLAYBACK = "RESUME_PLAYBACK";

const FETCH_SOURCES = "FETCH_SOURCES";

const UPDATE_TRACK_SOURCE = "UPDATE_TRACK_SOURCE";

const TRIGGER_BACKGROUND_EVENT = "TRIGGER_BACKGROUND_EVENT";

export { INIT_QUEUE_MODULE, INIT_PLAYER_MODULE, REGISTER_ON_PROGRESS_HANDLER, PLAY_TRACK, STOP_PLAYBACK,
    RESUME_PLAYBACK, FETCH_SOURCES, UPDATE_TRACK_SOURCE, TRIGGER_BACKGROUND_EVENT };
