/**
 * Created by qhyang on 2018/2/9.
 */

const UPDATE_QUEUE_GROUP = 'UPDATE_QUEUE_GROUP',
    INSERT_QUEUE = 'INSERT_QUEUE',
    UPDATE_QUEUE = 'UPDATE_QUEUE',
    UPDATE_PLAYING_QUEUE_INDEX = 'UPDATE_SELECT_QUEUE_INDEX',
    ADD_TRACK = 'ADD_TRACK',

    UPDATE_PANEL = 'UPDATE_PANEL',
    UPDATE_ACTIVE_PANEL_INDEX = 'UPDATE_ACTIVE_PANEL_INDEX',
    SET_ACTIVE_PANEL_INDEX_LOCK = 'SET_ACTIVE_PANEL_INDEX_LOCK';

export { UPDATE_QUEUE_GROUP, INSERT_QUEUE, UPDATE_QUEUE, UPDATE_PLAYING_QUEUE_INDEX, ADD_TRACK, UPDATE_PANEL, UPDATE_ACTIVE_PANEL_INDEX, SET_ACTIVE_PANEL_INDEX_LOCK };
