/**
 * Created by qhyang on 2018/2/9.
 */

const UPDATE_QUEUE_GROUP = 'UPDATE_QUEUE_GROUP',
    INSERT_QUEUE = 'INSERT_QUEUE',
    UPDATE_QUEUE = 'UPDATE_QUEUE';

export { UPDATE_QUEUE_GROUP, INSERT_QUEUE, UPDATE_QUEUE }
