/**
 * Created by qhyang on 2018/2/9.
 */

const ADD_SOURCES = 'ADD_SOURCES',

    UPDATE_QUEUE_GROUP = 'UPDATE_QUEUE_GROUP',
    INSERT_QUEUE = 'INSERT_QUEUE',
    UPDATE_QUEUE = 'UPDATE_QUEUE',
    UPDATE_PLAYING_QUEUE_INDEX = 'UPDATE_SELECT_QUEUE_INDEX',
    ADD_TRACK = 'ADD_TRACK',

    UPDATE_PANEL = 'UPDATE_PANEL',
    UPDATE_ACTIVE_PANEL_INDEX = 'UPDATE_ACTIVE_PANEL_INDEX',
    SET_ACTIVE_PANEL_INDEX_LOCK = 'SET_ACTIVE_PANEL_INDEX_LOCK',

    UPDATE_ACTIVE_BACKGROUND_TYPE = 'UPDATE_ACTIVE_BACKGROUND_TYPE',
    SWITCH_TO_VISUALIZER = 'SWITCH_TO_VISUALIZER',
    SWITCH_TO_BACKGROUND = 'SWITCH_TO_BACKGROUND',
    TRIGGER_BACKGROUND_EVENT = 'TRIGGER_BACKGROUND_EVENT';

export { ADD_SOURCES, UPDATE_QUEUE_GROUP, INSERT_QUEUE, UPDATE_QUEUE, UPDATE_PLAYING_QUEUE_INDEX, ADD_TRACK, UPDATE_PANEL, UPDATE_ACTIVE_PANEL_INDEX, SET_ACTIVE_PANEL_INDEX_LOCK, UPDATE_ACTIVE_BACKGROUND_TYPE, SWITCH_TO_VISUALIZER, SWITCH_TO_BACKGROUND, TRIGGER_BACKGROUND_EVENT };
