/**
 * Created by qhyang on 2018/2/9.
 */

const UPDATE_PROGRESS = "UPDATE_PROGRESS";
const UPDATE_STATE_DURATION = "UPDATE_STATE_DURATION";
const UPDATE_STATE_PROGRESS = "UPDATE_STATE_PROGRESS";
const PAUSE_PLAYBACK = "PAUSE_PLAYBACK";
const STOP_PLAYBACK = "STOP_PLAYBACK";

const ADD_SOURCES = "ADD_SOURCES";
const UPDATE_SOURCE = "UPDATE_SOURCE";

const UPDATE_QUEUE_GROUP = "UPDATE_QUEUE_GROUP";
const INSERT_QUEUE = "INSERT_QUEUE";
const UPDATE_QUEUE = "UPDATE_QUEUE";
const UPDATE_PLAYING_QUEUE_INDEX = "UPDATE_SELECT_QUEUE_INDEX";
const ADD_TRACK = "ADD_TRACK";
const NEXT_TRACK = "NEXT_TRACK";
const PREVIOUS_TRACK = "PREVIOUS_TRACK";
const UPDATE_TRACK = "UPDATE_TRACK";
const SWITCH_QUEUE_MODE = "SWITCH_QUEUE_MODE";

const PERSIST_PREFERENCE = "PERSIST_PREFERENCE";
const UPDATE_ACTIVE_PANEL_INDEX = "UPDATE_ACTIVE_PANEL_INDEX";
const SET_MODE = "SET_MODE";
const LOAD_LAYOUT = "LOAD_LAYOUT";
const SAVE_LAYOUT = "SAVE_LAYOUT";
const SET_MODAL_OPEN = "SET_MODAL_OPEN";
const SET_MODAL_BODY_COMPONENT = "SET_MODAL_BODY_COMPONENT";
const SET_MODAL_INPUT_VALUE = "SET_MODAL_INPUT_VALUE";
const SET_MODAL_RETURN_VALUE = "SET_MODAL_RETURN_VALUE";
const SET_MODAL_BUTTONS = "SET_MODAL_BUTTONS";
const SET_MODAL_APPEARANCE = "SET_MODAL_APPEARANCE";
const SET_ACTIVE_PANEL_INDEX_LOCK = "SET_ACTIVE_PANEL_INDEX_LOCK";
const SET_BACKGROUND_IMAGE = "SET_BACKGROUND_IMAGE";
const SET_LOCALE = "SET_LOCALE";
const SET_SHOW_SOURCE_ICON = "SET_SHOW_SOURCE_ICON";
const SET_SHOW_TIPS = "SET_SHOW_TIPS";
const SET_PERFORMANCE_FACTOR = "SET_PERFORMANCE_FACTOR";

const INIT_VISUALIZATION = "INIT_VISUALIZATION";
const UPDATE_ACTIVE_BACKGROUND_TYPE = "UPDATE_ACTIVE_BACKGROUND_TYPE";
const UPDATE_ACTIVE_VISUALIZER_TYPE = "UPDATE_ACTIVE_VISUALIZER_TYPE";
const BACKGROUND_LOAD_RESOURCE = "BACKGROUND_LOAD_RESOURCE";
const VISUALIZER_LOAD_RESOURCE = "VISUALIZER_LOAD_RESOURCE";

export { UPDATE_PROGRESS, UPDATE_STATE_DURATION, UPDATE_STATE_PROGRESS, PAUSE_PLAYBACK, STOP_PLAYBACK, ADD_SOURCES,
    UPDATE_SOURCE, UPDATE_QUEUE_GROUP, INSERT_QUEUE, UPDATE_QUEUE, UPDATE_PLAYING_QUEUE_INDEX, ADD_TRACK, NEXT_TRACK,
    PREVIOUS_TRACK, UPDATE_TRACK, SWITCH_QUEUE_MODE, PERSIST_PREFERENCE, UPDATE_ACTIVE_PANEL_INDEX, SET_MODE,
    LOAD_LAYOUT, SAVE_LAYOUT, SET_MODAL_OPEN, SET_MODAL_BODY_COMPONENT, SET_MODAL_INPUT_VALUE, SET_MODAL_RETURN_VALUE,
    SET_MODAL_BUTTONS, SET_MODAL_APPEARANCE, SET_ACTIVE_PANEL_INDEX_LOCK, SET_BACKGROUND_IMAGE, SET_LOCALE,
    SET_SHOW_SOURCE_ICON, SET_SHOW_TIPS, SET_PERFORMANCE_FACTOR, INIT_VISUALIZATION, UPDATE_ACTIVE_BACKGROUND_TYPE,
    UPDATE_ACTIVE_VISUALIZER_TYPE, BACKGROUND_LOAD_RESOURCE, VISUALIZER_LOAD_RESOURCE };
